image: mcr.microsoft.com/dotnet/core/sdk:3.1

cache:
  paths:
    - ~/.local/share/NuGet/Cache
    - ~/.nuget/packages

stages:
  - build
  - test

before_script:
  - "dotnet restore"

test:
  stage: test
  script:
    - "dotnet test"

