name: Master Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.*

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - run: dotnet restore ./Surreal.proj
      - run: dotnet build ./Surreal.proj /p:Version=0.2.${{ github.run_number }} --no-restore
      - run: dotnet test ./Surreal.proj /p:Version=0.2.${{ github.run_number }} --no-build --verbosity normal
      - run: dotnet pack ./Surreal.proj /p:Version=0.2.${{ github.run_number }} --output nuget-packages --configuration Release
      - run: dotnet nuget push **/*nupkg --skip-duplicate --api-key ${{ github.token }} --source https://nuget.pkg.github.com/mattkleiny/index.json
